import { RequiredDataFromCollectionSlug } from 'payload'

export const caseQuestionnaireForm: RequiredDataFromCollectionSlug<'forms'> = {
  title: 'Case Questionnaire Form',
  confirmationType: 'message',
  confirmationMessage: {
    root: {
      type: 'root',
      children: [
        {
          type: 'heading',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Your case questionnaire has been submitted successfully.',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          tag: 'h2',
          version: 1,
        },
      ],
      direction: 'ltr',
      format: '',
      indent: 0,
      version: 1,
    },
  },
  emails: [],
  redirect: undefined,
  submitButtonLabel: 'Submit Questionnaire',
  createdAt: '2023-01-12T21:47:41.374Z',
  updatedAt: '2023-01-12T21:47:41.374Z',
  fields: [
    { name: 'firstName', blockName: 'firstName', blockType: 'text', label: 'First Name', required: true, width: 50 },
    { name: 'lastName', blockName: 'lastName', blockType: 'text', label: 'Last Name', required: true, width: 50 },
    { name: 'spouseFirstName', blockName: 'spouseFirstName', blockType: 'text', label: 'Spouse First Name', required: false, width: 50 },
    { name: 'spouseLastName', blockName: 'spouseLastName', blockType: 'text', label: 'Spouse Last Name', required: false, width: 50 },
    { name: 'email', blockName: 'email', blockType: 'email', label: 'Email', required: true, width: 50 },
    { name: 'phoneNumber', blockName: 'phoneNumber', blockType: 'number', label: 'Phone Number', required: true, width: 50 },
    { name: 'streetAddress', blockName: 'streetAddress', blockType: 'text', label: 'Street Address', required: true, width: 100 },
    { name: 'city', blockName: 'city', blockType: 'text', label: 'City', required: true, width: 50 },
    { name: 'state', blockName: 'state', blockType: 'text', label: 'State', required: true, width: 50 },
    { name: 'zipCode', blockName: 'zipCode', blockType: 'text', label: 'ZIP Code', required: true, width: 50 },
    { name: 'workQuestion', blockName: 'workQuestion', blockType: 'text', label: 'Work Question', required: true, width: 100 },
    { name: 'requireInterpreter', blockName: 'requireInterpreter', blockType: 'text', label: 'Requires Interpreter', required: true, width: 50 },
    { name: 'employerName', blockName: 'employerName', blockType: 'text', label: 'Employer Name', required: true, width: 50 },
    { name: 'employerPhone', blockName: 'employerPhone', blockType: 'number', label: "Employer's Phone Number", required: true, width: 50 },
    { name: 'dateOfEmployment', blockName: 'dateOfEmployment', blockType: 'text', label: 'Date of Employment', required: true, width: 50 },
    { name: 'jobTitle', blockName: 'jobTitle', blockType: 'text', label: 'Job Title', required: true, width: 50 },
    { name: 'wageSalary', blockName: 'wageSalary', blockType: 'text', label: 'Wage / Salary', required: true, width: 50 },
    { name: 'hoursPerWeek', blockName: 'hoursPerWeek', blockType: 'text', label: 'Hours Per Week', required: false, width: 50 },
    { name: 'hasSecondJob', blockName: 'hasSecondJob', blockType: 'text', label: 'Has Second Job', required: true, width: 50 },
    { name: 'terminated', blockName: 'terminated', blockType: 'text', label: 'Terminated / Laid Off', required: true, width: 50 },
    { name: 'returnToWorkDate', blockName: 'returnToWorkDate', blockType: 'text', label: 'Return to Work Date', required: false, width: 100 },
    { name: 'lastDayOfWork', blockName: 'lastDayOfWork', blockType: 'text', label: 'Last Day of Work', required: false, width: 100 },
    { name: 'reportDate', blockName: 'reportDate', blockType: 'text', label: 'Date Accident Reported', required: false, width: 100 },
    { name: 'accidentType', blockName: 'accidentType', blockType: 'text', label: 'Type of Accident / Injury', required: true, width: 50 },
    { name: 'consultedAttorney', blockName: 'consultedAttorney', blockType: 'text', label: 'Consulted Attorney Before', required: false, width: 50 },
    { name: 'accidentDate', blockName: 'accidentDate', blockType: 'text', label: 'Date of Accident / Injury', required: false, width: 100 },
    { name: 'endingDateOfIllness', blockName: 'endingDateOfIllness', blockType: 'text', label: 'Ending Date of Illness', required: false, width: 50 },
    { name: 'injuryLocation', blockName: 'injuryLocation', blockType: 'text', label: 'Injury Location', required: false, width: 50 },
    { name: 'elsewhereDescription', blockName: 'elsewhereDescription', blockType: 'text', label: 'Injury Location Description', required: false, width: 50 },
    { name: 'timeOfInjury', blockName: 'timeOfInjury', blockType: 'text', label: 'Time of Injury', required: false, width: 50 },
    { name: 'partsOfBodyInjured', blockName: 'partsOfBodyInjured', blockType: 'text', label: 'Parts of Body Injured', required: false, width: 100 },
    { name: 'howInjuryOccurred', blockName: 'howInjuryOccurred', blockType: 'textarea', label: 'How Injury Occurred', required: true, width: 100 },
    { name: 'responsibleParties', blockName: 'responsibleParties', blockType: 'text', label: 'Responsible Parties', required: false, width: 100 },
    { name: 'responsibilityExplanation', blockName: 'responsibilityExplanation', blockType: 'textarea', label: 'Responsibility Explanation', required: false, width: 100 },
    { name: 'currentDoctors', blockName: 'currentDoctors', blockType: 'textarea', label: 'Current Doctors', required: false, width: 100 },
    { name: 'otherDoctors', blockName: 'otherDoctors', blockType: 'textarea', label: 'Other Doctors / Hospitals', required: false, width: 100 },
    { name: 'hospitalizedOvernight', blockName: 'hospitalizedOvernight', blockType: 'text', label: 'Hospitalized Overnight', required: true, width: 100 },
  ],
}
